### ISSUE TITLE
Location in photo upload throws error

### ISSUE THREAD

**Issue by kamami** [mohak1283/Instagram-Clone#3]
The loaction chips are throwing errors:

> Invalid argument(s)

**Comment by mohak1283** [comment]
Please provide more details of it. What errors are they throwing. When they are throwing errors

**Comment by slybaldguy** [comment]
This is the exception that I'm getting:

The following ArgumentError was thrown building FutureBuilder<List<Address>>(dirty, state: _FutureBuilderState<List<Address>>#ed3b5):
Invalid argument(s)

The relevant error-causing widget was: 
  FutureBuilder<List<Address>> file:///Users/tyler/AndroidStudioProjects/Instagram-Clone/lib/ui/insta_upload_photo_screen.dart:152:22
When the exception was thrown, this was the stack: 
#0      _StringBase.+ (dart:core-patch/string_patch.dart:262:57)
#1      _InstaUploadPhotoScreenState.build.<anonymous closure> (package:instagram_clone/ui/insta_upload_photo_screen.dart:176:42)
#2      _FutureBuilderState.build (package:flutter/src/widgets/async.dart:732:55)
#3      StatefulElement.build (package:flutter/src/widgets/framework.dart:4623:28)
#4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4506:15)
...
